### ISSUE TITLE
Application for the VideoGaze dataset

### ISSUE THREAD

**Issue by Vera123456789** [recasens/Gaze-Following#5]
The link to the VideoGaze dataset cannot be opened, could you send the dataset to me？thank you！

**Comment by recasens** [comment]
Hi! 

Thanks for your message. The server seems to be having some issues, we will try to address them and let you know once it's fixed.

Best wishes,

**Comment by zjz19960805** [comment]
Hello~
Have you finished fixing the dataset links?

**Comment by recasens** [comment]
Hi! Should be fixed now.
Thanks!
